on:
  pull_request:

jobs:
  create-deployment:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v1

      # Create a new GitHub deployment called "preview". Link it to the current
      # PR by setting `ref` to `github.head_ref`.
      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: preview
          ref: ${{ github.head_ref }}

      # Wait for the Netlify deployment to finish, and get the deployment URL.
      # If you are using a platform other than Netlify, this is the step that
      # you will need to replace.
      - name: Wait for Netlify deployment
        uses: jakepartusch/wait-for-netlify-action@v1.4
        id: netlify
        with:
          site_name: visionary-wisp-31b1e2

      # Finish the GitHub deployment and set the environment URL to the
      # deployment URL from the previous step.
      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: ${{ steps.netlify.outputs.url }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
