on:
  pull_request:

jobs:
  create-deployment:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v1

      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: preview
          ref: ${{ github.head_ref }}

      - name: Wait for Netlify deployment
        uses: jakepartusch/wait-for-netlify-action@v1.4
        id: netlify
        with:
          site_name: visionary-wisp-31b1e2

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: ${{ steps.netlify.outputs.url }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
